---
# https://developers.home-assistant.io/docs/add-ons/configuration#build-configuration
build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:3.20
  amd64: ghcr.io/home-assistant/amd64-base:3.20
