---
name: Test Builds

"on":
  pull_request:
    branches:
      - dev

  workflow_dispatch:
    inputs:
      amd64:
        type: boolean
        description: amd64
        required: false
        default: true
      aarch64:
        type: boolean
        description: aarch64
        required: false
        default: true

jobs:
  build:
    name: Test build

    runs-on: ubuntu-latest

    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v4

      - name: 🤔 Determine which images to build
        id: build-args
        shell: bash
        run: |-
          args=()

          if [[ ${{ github.event_name }} == "pull_request" ]]; then
            args+=("--amd64" "--aarch64")  # Build all supported archs by default
          else
            if [[ "${{ github.event.inputs.aarch64 }}" == "true" ]]; then
              args+=("--aarch64")
            fi

            if [[ "${{ github.event.inputs.amd64 }}" == "true" ]]; then
              args+=("--amd64")
            fi
          fi

          echo "arguments=${args[@]}" >> $GITHUB_OUTPUT

      - name: 🚧 Test build
        uses: home-assistant/builder@6cb4fd3d1338b6e22d0958a4bcb53e0965ea63b4 # 2026.02.1
        with:
          args: |
            --test \
            --target ecowitt2mqtt \
            ${{ steps.build-args.outputs.arguments }}
